import localFont from "next/font/local";
import "./globals.css";
import { Providers } from "./Provider";
import Nav from "@/components/Navbarcomponents/Nav";
import BrandMarquee from "@/components/BrandMarquee/BrandMarquee";
import Footer from "@/components/Footer/Footer";
import MobileFooter from "@/components/MobileFooter/MobileFooter";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});

const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Shivraj Mobile Shopee",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link
          href="https://fonts.googleapis.com/css2?family=Yatra+One&display=swap"
          rel="stylesheet"
        />
        <link
          href="https://fonts.googleapis.com/css2?family=Rozha+One&family=Yatra+One&display=swap"
          rel="stylesheet"
        />
        <link
          href="https://fonts.googleapis.com/css2?family=Kalam:wght@300;400;700&display=swap"
          rel="stylesheet"
        />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Providers>
          <div className="lg:flex hidden">
            <BrandMarquee />
          </div>
          <div>
            <Nav />
          </div>

          {children}
          <div className="hidden ">
            <Footer />
          </div>

          <MobileFooter />
        </Providers>
      </body>
    </html>
  );
}
